export function getRegionCodes() {
  return [
    "ad",
    "ae",
    "af",
    "ag",
    "ai",
    "al",
    "am",
    "ao",
    "aq",
    "ar",
    "as",
    "at",
    "au",
    "aw",
    "ax",
    "az",
    "ba",
    "bb",
    "bd",
    "be",
    "bf",
    "bg",
    "bh",
    "bi",
    "bj",
    "bl",
    "bm",
    "bn",
    "bo",
    "bq",
    "br",
    "bs",
    "bt",
    "bv",
    "bw",
    "by",
    "bz",
    "ca",
    "cc",
    "cd",
    "cf",
    "cg",
    "ch",
    "ci",
    "ck",
    "cl",
    "cm",
    "cn",
    "co",
    "cr",
    "cu",
    "cv",
    "cw",
    "cx",
    "cy",
    "cz",
    "de",
    "dj",
    "dk",
    "dm",
    "do",
    "dz",
    "ec",
    "ee",
    "eg",
    "eh",
    "er",
    "es",
    "et",
    "fi",
    "fj",
    "fk",
    "fm",
    "fo",
    "fr",
    "ga",
    "gb",
    "gd",
    "ge",
    "gf",
    "gg",
    "gh",
    "gi",
    "gl",
    "gm",
    "gn",
    "gp",
    "gq",
    "gr",
    "gs",
    "gt",
    "gu",
    "gw",
    "gy",
    "hk",
    "hm",
    "hn",
    "hr",
    "ht",
    "hu",
    "id",
    "ie",
    "il",
    "im",
    "in",
    "io",
    "iq",
    "ir",
    "is",
    "it",
    "je",
    "jm",
    "jo",
    "jp",
    "ke",
    "kg",
    "kh",
    "ki",
    "km",
    "kn",
    "kp",
    "kr",
    "kw",
    "ky",
    "kz",
    "la",
    "lb",
    "lc",
    "li",
    "lk",
    "lr",
    "ls",
    "lt",
    "lu",
    "lv",
    "ly",
    "ma",
    "mc",
    "md",
    "me",
    "mf",
    "mg",
    "mh",
    "mk",
    "ml",
    "mm",
    "mn",
    "mo",
    "mp",
    "mq",
    "mr",
    "ms",
    "mt",
    "mu",
    "mv",
    "mw",
    "mx",
    "my",
    "mz",
    "na",
    "nc",
    "ne",
    "nf",
    "ng",
    "ni",
    "nl",
    "no",
    "np",
    "nr",
    "nu",
    "nz",
    "om",
    "pa",
    "pe",
    "pf",
    "pg",
    "ph",
    "pk",
    "pl",
    "pm",
    "pn",
    "pr",
    "ps",
    "pt",
    "pw",
    "py",
    "qa",
    "re",
    "ro",
    "rs",
    "ru",
    "rw",
    "sa",
    "sb",
    "sc",
    "sd",
    "se",
    "sg",
    "sh",
    "si",
    "sj",
    "sk",
    "sl",
    "sm",
    "sn",
    "so",
    "sr",
    "ss",
    "st",
    "sv",
    "sx",
    "sy",
    "sz",
    "tc",
    "td",
    "tf",
    "tg",
    "th",
    "tj",
    "tk",
    "tl",
    "tm",
    "tn",
    "to",
    "tr",
    "tt",
    "tv",
    "tw",
    "tz",
    "ua",
    "ug",
    "um",
    "us",
    "uy",
    "uz",
    "va",
    "vc",
    "ve",
    "vg",
    "vi",
    "vn",
    "vu",
    "wf",
    "ws",
    "xk",
    "ye",
    "yt",
    "za",
    "zm",
    "zw",
  ];
}

export function getNameFromIso(isoCode: string) {
  const countryNames: { [key: string]: string } = {
    ad: "Andorra",
    ae: "United Arab Emirates",
    af: "Afghanistan",
    ag: "Antigua and Barbuda",
    ai: "Anguilla",
    al: "Albania",
    am: "Armenia",
    ao: "Angola",
    aq: "Antarctica",
    ar: "Argentina",
    as: "American Samoa",
    at: "Austria",
    au: "Australia",
    aw: "Aruba",
    ax: "Aland Islands",
    az: "Azerbaijan",
    ba: "Bosnia and Herzegovina",
    bb: "Barbados",
    bd: "Bangladesh",
    be: "Belgium",
    bf: "Burkina Faso",
    bg: "Bulgaria",
    bh: "Bahrain",
    bi: "Burundi",
    bj: "Benin",
    bl: "Saint Barthelemy",
    bm: "Bermuda",
    bn: "Brunei",
    bo: "Bolivia",
    bq: "Bonaire, Sint Eustatius, and Saba",
    br: "Brazil",
    bs: "Bahamas",
    bt: "Bhutan",
    bv: "Bouvet Island",
    bw: "Botswana",
    by: "Belarus",
    bz: "Belize",
    ca: "Canada",
    cc: "Cocos (Keeling) Islands",
    cd: "Democratic Republic of the Congo",
    cf: "Central African Republic",
    cg: "Republic of the Congo",
    ch: "Switzerland",
    ci: "Ivory Coast",
    ck: "Cook Islands",
    cl: "Chile",
    cm: "Cameroon",
    cn: "China",
    co: "Colombia",
    cr: "Costa Rica",
    cu: "Cuba",
    cv: "Cape Verde",
    cw: "Curacao",
    cx: "Christmas Island",
    cy: "Cyprus",
    cz: "Czech Republic",
    de: "Germany",
    dj: "Djibouti",
    dk: "Denmark",
    dm: "Dominica",
    do: "Dominican Republic",
    dz: "Algeria",
    ec: "Ecuador",
    ee: "Estonia",
    eg: "Egypt",
    eh: "Western Sahara",
    er: "Eritrea",
    es: "Spain",
    et: "Ethiopia",
    fi: "Finland",
    fj: "Fiji",
    fk: "Falkland Islands",
    fm: "Micronesia",
    fo: "Faroe Islands",
    fr: "France",
    ga: "Gabon",
    gb: "United Kingdom",
    gd: "Grenada",
    ge: "Georgia",
    gf: "French Guiana",
    gg: "Guernsey",
    gh: "Ghana",
    gi: "Gibraltar",
    gl: "Greenland",
    gm: "Gambia",
    gn: "Guinea",
    gp: "Guadeloupe",
    gq: "Equatorial Guinea",
    gr: "Greece",
    gs: "South Georgia and the South Sandwich Islands",
    gt: "Guatemala",
    gu: "Guam",
    gw: "Guinea-Bissau",
    gy: "Guyana",
    hk: "Hong Kong",
    hm: "Heard Island and McDonald Islands",
    hn: "Honduras",
    hr: "Croatia",
    ht: "Haiti",
    hu: "Hungary",
    id: "Indonesia",
    ie: "Ireland",
    il: "Israel",
    im: "Isle of Man",
    in: "India",
    io: "British Indian Ocean Territory",
    iq: "Iraq",
    ir: "Iran",
    is: "Iceland",
    it: "Italy",
    je: "Jersey",
    jm: "Jamaica",
    jo: "Jordan",
    jp: "Japan",
    ke: "Kenya",
    kg: "Kyrgyzstan",
    kh: "Cambodia",
    ki: "Kiribati",
    km: "Comoros",
    kn: "Saint Kitts and Nevis",
    kp: "North Korea",
    kr: "South Korea",
    kw: "Kuwait",
    ky: "Cayman Islands",
    kz: "Kazakhstan",
    la: "Laos",
    lb: "Lebanon",
    lc: "Saint Lucia",
    li: "Liechtenstein",
    lk: "Sri Lanka",
    lr: "Liberia",
    ls: "Lesotho",
    lt: "Lithuania",
    lu: "Luxembourg",
    lv: "Latvia",
    ly: "Libya",
    ma: "Morocco",
    mc: "Monaco",
    md: "Moldova",
    me: "Montenegro",
    mf: "Saint Martin",
    mg: "Madagascar",
    mh: "Marshall Islands",
    mk: "North Macedonia",
    ml: "Mali",
    mm: "Myanmar",
    mn: "Mongolia",
    mo: "Macau",
    mp: "Northern Mariana Islands",
    mq: "Martinique",
    mr: "Mauritania",
    ms: "Montserrat",
    mt: "Malta",
    mu: "Mauritius",
    mv: "Maldives",
    mw: "Malawi",
    mx: "Mexico",
    my: "Malaysia",
    mz: "Mozambique",
    na: "Namibia",
    nc: "New Caledonia",
    ne: "Niger",
    nf: "Norfolk Island",
    ng: "Nigeria",
    ni: "Nicaragua",
    nl: "Netherlands",
    no: "Norway",
    np: "Nepal",
    nr: "Nauru",
    nu: "Niue",
    nz: "New Zealand",
    om: "Oman",
    pa: "Panama",
    pe: "Peru",
    pf: "French Polynesia",
    pg: "Papua New Guinea",
    ph: "Philippines",
    pk: "Pakistan",
    pl: "Poland",
    pm: "Saint Pierre and Miquelon",
    pn: "Pitcairn Islands",
    pr: "Puerto Rico",
    ps: "Palestine",
    pt: "Portugal",
    pw: "Palau",
    py: "Paraguay",
    qa: "Qatar",
    re: "Reunion",
    ro: "Romania",
    rs: "Serbia",
    ru: "Russia",
    rw: "Rwanda",
    sa: "Saudi Arabia",
    sb: "Solomon Islands",
    sc: "Seychelles",
    sd: "Sudan",
    se: "Sweden",
    sg: "Singapore",
    sh: "Saint Helena",
    si: "Slovenia",
    sj: "Svalbard and Jan Mayen",
    sk: "Slovakia",
    sl: "Sierra Leone",
    sm: "San Marino",
    sn: "Senegal",
    so: "Somalia",
    sr: "Suriname",
    ss: "South Sudan",
    st: "Sao Tome and Principe",
    sv: "El Salvador",
    sx: "Sint Maarten",
    sy: "Syria",
    sz: "Eswatini",
    tc: "Turks and Caicos Islands",
    td: "Chad",
    tf: "French Southern Territories",
    tg: "Togo",
    th: "Thailand",
    tj: "Tajikistan",
    tk: "Tokelau",
    tl: "East Timor",
    tm: "Turkmenistan",
    tn: "Tunisia",
    to: "Tonga",
    tr: "Turkey",
    tt: "Trinidad and Tobago",
    tv: "Tuvalu",
    tw: "Taiwan",
    tz: "Tanzania",
    ua: "Ukraine",
    ug: "Uganda",
    um: "United States Minor Outlying Islands",
    us: "United States",
    uy: "Uruguay",
    uz: "Uzbekistan",
    va: "Vatican City",
    vc: "Saint Vincent and the Grenadines",
    ve: "Venezuela",
    vg: "British Virgin Islands",
    vi: "United States Virgin Islands",
    vn: "Vietnam",
    vu: "Vanuatu",
    wf: "Wallis and Futuna",
    ws: "Samoa",
    xk: "Kosovo",
    ye: "Yemen",
    yt: "Mayotte",
    za: "South Africa",
    zm: "Zambia",
    zw: "Zimbabwe",
  };

  return countryNames[isoCode] || null;
}

export function getIsoFromName(countryName: string): string | null {
  const isoCodes: { [key: string]: string } = {
    Andorra: "ad",
    "United Arab Emirates": "ae",
    Afghanistan: "af",
    "Antigua and Barbuda": "ag",
    Anguilla: "ai",
    Albania: "al",
    Armenia: "am",
    Angola: "ao",
    Antarctica: "aq",
    Argentina: "ar",
    "American Samoa": "as",
    Austria: "at",
    Australia: "au",
    Aruba: "aw",
    "Aland Islands": "ax",
    Azerbaijan: "az",
    "Bosnia and Herzegovina": "ba",
    Barbados: "bb",
    Bangladesh: "bd",
    Belgium: "be",
    "Burkina Faso": "bf",
    Bulgaria: "bg",
    Bahrain: "bh",
    Burundi: "bi",
    Benin: "bj",
    "Saint Barthelemy": "bl",
    Bermuda: "bm",
    Brunei: "bn",
    Bolivia: "bo",
    "Bonaire, Sint Eustatius, and Saba": "bq",
    Brazil: "br",
    Bahamas: "bs",
    Bhutan: "bt",
    "Bouvet Island": "bv",
    Botswana: "bw",
    Belarus: "by",
    Belize: "bz",
    Canada: "ca",
    "Cocos (Keeling) Islands": "cc",
    "Democratic Republic of the Congo": "cd",
    "Central African Republic": "cf",
    "Republic of the Congo": "cg",
    Switzerland: "ch",
    "Ivory Coast": "ci",
    "Cook Islands": "ck",
    Chile: "cl",
    Cameroon: "cm",
    China: "cn",
    Colombia: "co",
    "Costa Rica": "cr",
    Cuba: "cu",
    "Cape Verde": "cv",
    Curacao: "cw",
    "Christmas Island": "cx",
    Cyprus: "cy",
    "Czech Republic": "cz",
    Germany: "de",
    Djibouti: "dj",
    Denmark: "dk",
    Dominica: "dm",
    "Dominican Republic": "do",
    Algeria: "dz",
    Ecuador: "ec",
    Estonia: "ee",
    Egypt: "eg",
    "Western Sahara": "eh",
    Eritrea: "er",
    Spain: "es",
    Ethiopia: "et",
    Finland: "fi",
    Fiji: "fj",
    "Falkland Islands": "fk",
    Micronesia: "fm",
    "Faroe Islands": "fo",
    France: "fr",
    Gabon: "ga",
    "United Kingdom": "gb",
    Grenada: "gd",
    Georgia: "ge",
    "French Guiana": "gf",
    Guernsey: "gg",
    Ghana: "gh",
    Gibraltar: "gi",
    Greenland: "gl",
    Gambia: "gm",
    Guinea: "gn",
    Guadeloupe: "gp",
    "Equatorial Guinea": "gq",
    Greece: "gr",
    "South Georgia and the South Sandwich Islands": "gs",
    Guatemala: "gt",
    Guam: "gu",
    "Guinea-Bissau": "gw",
    Guyana: "gy",
    "Hong Kong": "hk",
    "Heard Island and McDonald Islands": "hm",
    Honduras: "hn",
    Croatia: "hr",
    Haiti: "ht",
    Hungary: "hu",
    Indonesia: "id",
    Ireland: "ie",
    Israel: "il",
    "Isle of Man": "im",
    India: "in",
    "British Indian Ocean Territory": "io",
    Iraq: "iq",
    Iran: "ir",
    Iceland: "is",
    Italy: "it",
    Jersey: "je",
    Jamaica: "jm",
    Jordan: "jo",
    Japan: "jp",
    Kenya: "ke",
    Kyrgyzstan: "kg",
    Cambodia: "kh",
    Kiribati: "ki",
    Comoros: "km",
    "Saint Kitts and Nevis": "kn",
    "North Korea": "kp",
    "South Korea": "kr",
    Kuwait: "kw",
    "Cayman Islands": "ky",
    Kazakhstan: "kz",
    Laos: "la",
    Lebanon: "lb",
    "Saint Lucia": "lc",
    Liechtenstein: "li",
    "Sri Lanka": "lk",
    Liberia: "lr",
    Lesotho: "ls",
    Lithuania: "lt",
    Luxembourg: "lu",
    Latvia: "lv",
    Libya: "ly",
    Morocco: "ma",
    Monaco: "mc",
    Moldova: "md",
    Montenegro: "me",
    "Saint Martin": "mf",
    Madagascar: "mg",
    "Marshall Islands": "mh",
    "North Macedonia": "mk",
    Mali: "ml",
    Myanmar: "mm",
    Mongolia: "mn",
    Macau: "mo",
    "Northern Mariana Islands": "mp",
    Martinique: "mq",
    Mauritania: "mr",
    Montserrat: "ms",
    Malta: "mt",
    Mauritius: "mu",
    Maldives: "mv",
    Malawi: "mw",
    Mexico: "mx",
    Malaysia: "my",
    Mozambique: "mz",
    Namibia: "na",
    "New Caledonia": "nc",
    Niger: "ne",
    "Norfolk Island": "nf",
    Nigeria: "ng",
    Nicaragua: "ni",
    Netherlands: "nl",
    Norway: "no",
    Nepal: "np",
    Nauru: "nr",
    Niue: "nu",
    "New Zealand": "nz",
    Oman: "om",
    Panama: "pa",
    Peru: "pe",
    "French Polynesia": "pf",
    "Papua New Guinea": "pg",
    Philippines: "ph",
    Pakistan: "pk",
    Poland: "pl",
    "Saint Pierre and Miquelon": "pm",
    "Pitcairn Islands": "pn",
    "Puerto Rico": "pr",
    Palestine: "ps",
    Portugal: "pt",
    Palau: "pw",
    Paraguay: "py",
    Qatar: "qa",
    Reunion: "re",
    Romania: "ro",
    Serbia: "rs",
    Russia: "ru",
    Rwanda: "rw",
    "Saudi Arabia": "sa",
    "Solomon Islands": "sb",
    Seychelles: "sc",
    Sudan: "sd",
    Sweden: "se",
    Singapore: "sg",
    "Saint Helena": "sh",
    Slovenia: "si",
    "Svalbard and Jan Mayen": "sj",
    Slovakia: "sk",
    "Sierra Leone": "sl",
    "San Marino": "sm",
    Senegal: "sn",
    Somalia: "so",
    Suriname: "sr",
    "South Sudan": "ss",
    "Sao Tome and Principe": "st",
    "El Salvador": "sv",
    "Sint Maarten": "sx",
    Syria: "sy",
    Eswatini: "sz",
    "Turks and Caicos Islands": "tc",
    Chad: "td",
    "French Southern Territories": "tf",
    Togo: "tg",
    Thailand: "th",
    Tajikistan: "tj",
    Tokelau: "tk",
    "East Timor": "tl",
    Turkmenistan: "tm",
    Tunisia: "tn",
    Tonga: "to",
    Turkey: "tr",
    "Trinidad and Tobago": "tt",
    Tuvalu: "tv",
    Taiwan: "tw",
    Tanzania: "tz",
    Ukraine: "ua",
    Uganda: "ug",
    "United States Minor Outlying Islands": "um",
    "United States": "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
    "Vatican City": "va",
    "Saint Vincent and the Grenadines": "vc",
    Venezuela: "ve",
    "British Virgin Islands": "vg",
    "United States Virgin Islands": "vi",
    Vietnam: "vn",
    Vanuatu: "vu",
    "Wallis and Futuna": "wf",
    Samoa: "ws",
    Kosovo: "xk",
    Yemen: "ye",
    Mayotte: "yt",
    "South Africa": "za",
    Zambia: "zm",
    Zimbabwe: "zw",
  };

  return isoCodes[countryName] || null;
}

interface RegionPg {
  params: { regionPg: string };
}

export async function getRegionPgPaths(): Promise<RegionPg[]> {
  return [
    { params: { regionPg: "ad-1" } },
    { params: { regionPg: "ae-1" } },
    { params: { regionPg: "af-1" } },
    { params: { regionPg: "ag-1" } },
    { params: { regionPg: "ai-1" } },
    { params: { regionPg: "al-1" } },
    { params: { regionPg: "am-1" } },
    { params: { regionPg: "ao-1" } },
    { params: { regionPg: "aq-1" } },
    { params: { regionPg: "ar-1" } },
    { params: { regionPg: "as-1" } },
    { params: { regionPg: "at-1" } },
    { params: { regionPg: "au-1" } },
    { params: { regionPg: "aw-1" } },
    { params: { regionPg: "ax-1" } },
    { params: { regionPg: "az-1" } },
    { params: { regionPg: "ba-1" } },
    { params: { regionPg: "bb-1" } },
    { params: { regionPg: "bd-1" } },
    { params: { regionPg: "be-1" } },
    { params: { regionPg: "bf-1" } },
    { params: { regionPg: "bg-1" } },
    { params: { regionPg: "bh-1" } },
    { params: { regionPg: "bi-1" } },
    { params: { regionPg: "bj-1" } },
    { params: { regionPg: "bl-1" } },
    { params: { regionPg: "bm-1" } },
    { params: { regionPg: "bn-1" } },
    { params: { regionPg: "bo-1" } },
    { params: { regionPg: "bq-1" } },
    { params: { regionPg: "br-1" } },
    { params: { regionPg: "bs-1" } },
    { params: { regionPg: "bt-1" } },
    { params: { regionPg: "bv-1" } },
    { params: { regionPg: "bw-1" } },
    { params: { regionPg: "by-1" } },
    { params: { regionPg: "bz-1" } },
    { params: { regionPg: "ca-1" } },
    { params: { regionPg: "cc-1" } },
    { params: { regionPg: "cd-1" } },
    { params: { regionPg: "cf-1" } },
    { params: { regionPg: "cg-1" } },
    { params: { regionPg: "ch-1" } },
    { params: { regionPg: "ci-1" } },
    { params: { regionPg: "ck-1" } },
    { params: { regionPg: "cl-1" } },
    { params: { regionPg: "cm-1" } },
    { params: { regionPg: "cn-1" } },
    { params: { regionPg: "co-1" } },
    { params: { regionPg: "cr-1" } },
    { params: { regionPg: "cu-1" } },
    { params: { regionPg: "cv-1" } },
    { params: { regionPg: "cw-1" } },
    { params: { regionPg: "cx-1" } },
    { params: { regionPg: "cy-1" } },
    { params: { regionPg: "cz-1" } },
    { params: { regionPg: "de-1" } },
    { params: { regionPg: "dj-1" } },
    { params: { regionPg: "dk-1" } },
    { params: { regionPg: "dm-1" } },
    { params: { regionPg: "do-1" } },
    { params: { regionPg: "dz-1" } },
    { params: { regionPg: "ec-1" } },
    { params: { regionPg: "ee-1" } },
    { params: { regionPg: "eg-1" } },
    { params: { regionPg: "eh-1" } },
    { params: { regionPg: "er-1" } },
    { params: { regionPg: "es-1" } },
    { params: { regionPg: "et-1" } },
    { params: { regionPg: "fi-1" } },
    { params: { regionPg: "fj-1" } },
    { params: { regionPg: "fk-1" } },
    { params: { regionPg: "fm-1" } },
    { params: { regionPg: "fo-1" } },
    { params: { regionPg: "fr-1" } },
    { params: { regionPg: "ga-1" } },
    { params: { regionPg: "gb-1" } },
    { params: { regionPg: "gd-1" } },
    { params: { regionPg: "ge-1" } },
    { params: { regionPg: "gf-1" } },
    { params: { regionPg: "gg-1" } },
    { params: { regionPg: "gh-1" } },
    { params: { regionPg: "gi-1" } },
    { params: { regionPg: "gl-1" } },
    { params: { regionPg: "gm-1" } },
    { params: { regionPg: "gn-1" } },
    { params: { regionPg: "gp-1" } },
    { params: { regionPg: "gq-1" } },
    { params: { regionPg: "gr-1" } },
    { params: { regionPg: "gs-1" } },
    { params: { regionPg: "gt-1" } },
    { params: { regionPg: "gu-1" } },
    { params: { regionPg: "gw-1" } },
    { params: { regionPg: "gy-1" } },
    { params: { regionPg: "hk-1" } },
    { params: { regionPg: "hm-1" } },
    { params: { regionPg: "hn-1" } },
    { params: { regionPg: "hr-1" } },
    { params: { regionPg: "ht-1" } },
    { params: { regionPg: "hu-1" } },
    { params: { regionPg: "id-1" } },
    { params: { regionPg: "ie-1" } },
    { params: { regionPg: "il-1" } },
    { params: { regionPg: "im-1" } },
    { params: { regionPg: "in-1" } },
    { params: { regionPg: "io-1" } },
    { params: { regionPg: "iq-1" } },
    { params: { regionPg: "ir-1" } },
    { params: { regionPg: "is-1" } },
    { params: { regionPg: "it-1" } },
    { params: { regionPg: "je-1" } },
    { params: { regionPg: "jm-1" } },
    { params: { regionPg: "jo-1" } },
    { params: { regionPg: "jp-1" } },
    { params: { regionPg: "ke-1" } },
    { params: { regionPg: "kg-1" } },
    { params: { regionPg: "kh-1" } },
    { params: { regionPg: "ki-1" } },
    { params: { regionPg: "km-1" } },
    { params: { regionPg: "kn-1" } },
    { params: { regionPg: "kp-1" } },
    { params: { regionPg: "kr-1" } },
    { params: { regionPg: "kw-1" } },
    { params: { regionPg: "ky-1" } },
    { params: { regionPg: "kz-1" } },
    { params: { regionPg: "la-1" } },
    { params: { regionPg: "lb-1" } },
    { params: { regionPg: "lc-1" } },
    { params: { regionPg: "li-1" } },
    { params: { regionPg: "lk-1" } },
    { params: { regionPg: "lr-1" } },
    { params: { regionPg: "ls-1" } },
    { params: { regionPg: "lt-1" } },
    { params: { regionPg: "lu-1" } },
    { params: { regionPg: "lv-1" } },
    { params: { regionPg: "ly-1" } },
    { params: { regionPg: "ma-1" } },
    { params: { regionPg: "mc-1" } },
    { params: { regionPg: "md-1" } },
    { params: { regionPg: "me-1" } },
    { params: { regionPg: "mf-1" } },
    { params: { regionPg: "mg-1" } },
    { params: { regionPg: "mh-1" } },
    { params: { regionPg: "mk-1" } },
    { params: { regionPg: "ml-1" } },
    { params: { regionPg: "mm-1" } },
    { params: { regionPg: "mn-1" } },
    { params: { regionPg: "mo-1" } },
    { params: { regionPg: "mp-1" } },
    { params: { regionPg: "mq-1" } },
    { params: { regionPg: "mr-1" } },
    { params: { regionPg: "ms-1" } },
    { params: { regionPg: "mt-1" } },
    { params: { regionPg: "mu-1" } },
    { params: { regionPg: "mv-1" } },
    { params: { regionPg: "mw-1" } },
    { params: { regionPg: "mx-1" } },
    { params: { regionPg: "my-1" } },
    { params: { regionPg: "mz-1" } },
    { params: { regionPg: "na-1" } },
    { params: { regionPg: "nc-1" } },
    { params: { regionPg: "ne-1" } },
    { params: { regionPg: "nf-1" } },
    { params: { regionPg: "ng-1" } },
    { params: { regionPg: "ni-1" } },
    { params: { regionPg: "nl-1" } },
    { params: { regionPg: "no-1" } },
    { params: { regionPg: "np-1" } },
    { params: { regionPg: "nr-1" } },
    { params: { regionPg: "nu-1" } },
    { params: { regionPg: "nz-1" } },
    { params: { regionPg: "om-1" } },
    { params: { regionPg: "pa-1" } },
    { params: { regionPg: "pe-1" } },
    { params: { regionPg: "pf-1" } },
    { params: { regionPg: "pg-1" } },
    { params: { regionPg: "ph-1" } },
    { params: { regionPg: "pk-1" } },
    { params: { regionPg: "pl-1" } },
    { params: { regionPg: "pm-1" } },
    { params: { regionPg: "pn-1" } },
    { params: { regionPg: "pr-1" } },
    { params: { regionPg: "ps-1" } },
    { params: { regionPg: "pt-1" } },
    { params: { regionPg: "pw-1" } },
    { params: { regionPg: "py-1" } },
    { params: { regionPg: "qa-1" } },
    { params: { regionPg: "re-1" } },
    { params: { regionPg: "ro-1" } },
    { params: { regionPg: "rs-1" } },
    { params: { regionPg: "ru-1" } },
    { params: { regionPg: "rw-1" } },
    { params: { regionPg: "sa-1" } },
    { params: { regionPg: "sb-1" } },
    { params: { regionPg: "sc-1" } },
    { params: { regionPg: "sd-1" } },
    { params: { regionPg: "se-1" } },
    { params: { regionPg: "sg-1" } },
    { params: { regionPg: "sh-1" } },
    { params: { regionPg: "si-1" } },
    { params: { regionPg: "sj-1" } },
    { params: { regionPg: "sk-1" } },
    { params: { regionPg: "sl-1" } },
    { params: { regionPg: "sm-1" } },
    { params: { regionPg: "sn-1" } },
    { params: { regionPg: "so-1" } },
    { params: { regionPg: "sr-1" } },
    { params: { regionPg: "ss-1" } },
    { params: { regionPg: "st-1" } },
    { params: { regionPg: "sv-1" } },
    { params: { regionPg: "sx-1" } },
    { params: { regionPg: "sy-1" } },
    { params: { regionPg: "sz-1" } },
    { params: { regionPg: "tc-1" } },
    { params: { regionPg: "td-1" } },
    { params: { regionPg: "tf-1" } },
    { params: { regionPg: "tg-1" } },
    { params: { regionPg: "th-1" } },
    { params: { regionPg: "tj-1" } },
    { params: { regionPg: "tk-1" } },
    { params: { regionPg: "tl-1" } },
    { params: { regionPg: "tm-1" } },
    { params: { regionPg: "tn-1" } },
    { params: { regionPg: "to-1" } },
    { params: { regionPg: "tr-1" } },
    { params: { regionPg: "tt-1" } },
    { params: { regionPg: "tv-1" } },
    { params: { regionPg: "tw-1" } },
    { params: { regionPg: "tz-1" } },
    { params: { regionPg: "ua-1" } },
    { params: { regionPg: "ug-1" } },
    { params: { regionPg: "um-1" } },
    { params: { regionPg: "us-1" } },
    { params: { regionPg: "uy-1" } },
    { params: { regionPg: "uz-1" } },
    { params: { regionPg: "va-1" } },
    { params: { regionPg: "vc-1" } },
    { params: { regionPg: "ve-1" } },
    { params: { regionPg: "vg-1" } },
    { params: { regionPg: "vi-1" } },
    { params: { regionPg: "vn-1" } },
    { params: { regionPg: "vu-1" } },
    { params: { regionPg: "wf-1" } },
    { params: { regionPg: "ws-1" } },
    { params: { regionPg: "xk-1" } },
    { params: { regionPg: "ye-1" } },
    { params: { regionPg: "yt-1" } },
    { params: { regionPg: "za-1" } },
    { params: { regionPg: "zm-1" } },
    { params: { regionPg: "zw-1" } },
    { params: { regionPg: "ad-2" } },
    { params: { regionPg: "ae-2" } },
    { params: { regionPg: "af-2" } },
    { params: { regionPg: "ag-2" } },
    { params: { regionPg: "ai-2" } },
    { params: { regionPg: "al-2" } },
    { params: { regionPg: "am-2" } },
    { params: { regionPg: "ao-2" } },
    { params: { regionPg: "aq-2" } },
    { params: { regionPg: "ar-2" } },
    { params: { regionPg: "as-2" } },
    { params: { regionPg: "at-2" } },
    { params: { regionPg: "au-2" } },
    { params: { regionPg: "aw-2" } },
    { params: { regionPg: "ax-2" } },
    { params: { regionPg: "az-2" } },
    { params: { regionPg: "ba-2" } },
    { params: { regionPg: "bb-2" } },
    { params: { regionPg: "bd-2" } },
    { params: { regionPg: "be-2" } },
    { params: { regionPg: "bf-2" } },
    { params: { regionPg: "bg-2" } },
    { params: { regionPg: "bh-2" } },
    { params: { regionPg: "bi-2" } },
    { params: { regionPg: "bj-2" } },
    { params: { regionPg: "bl-2" } },
    { params: { regionPg: "bm-2" } },
    { params: { regionPg: "bn-2" } },
    { params: { regionPg: "bo-2" } },
    { params: { regionPg: "bq-2" } },
    { params: { regionPg: "br-2" } },
    { params: { regionPg: "bs-2" } },
    { params: { regionPg: "bt-2" } },
    { params: { regionPg: "bv-2" } },
    { params: { regionPg: "bw-2" } },
    { params: { regionPg: "by-2" } },
    { params: { regionPg: "bz-2" } },
    { params: { regionPg: "ca-2" } },
    { params: { regionPg: "cc-2" } },
    { params: { regionPg: "cd-2" } },
    { params: { regionPg: "cf-2" } },
    { params: { regionPg: "cg-2" } },
    { params: { regionPg: "ch-2" } },
    { params: { regionPg: "ci-2" } },
    { params: { regionPg: "ck-2" } },
    { params: { regionPg: "cl-2" } },
    { params: { regionPg: "cm-2" } },
    { params: { regionPg: "cn-2" } },
    { params: { regionPg: "co-2" } },
    { params: { regionPg: "cr-2" } },
    { params: { regionPg: "cu-2" } },
    { params: { regionPg: "cv-2" } },
    { params: { regionPg: "cw-2" } },
    { params: { regionPg: "cx-2" } },
    { params: { regionPg: "cy-2" } },
    { params: { regionPg: "cz-2" } },
    { params: { regionPg: "de-2" } },
    { params: { regionPg: "dj-2" } },
    { params: { regionPg: "dk-2" } },
    { params: { regionPg: "dm-2" } },
    { params: { regionPg: "do-2" } },
    { params: { regionPg: "dz-2" } },
    { params: { regionPg: "ec-2" } },
    { params: { regionPg: "ee-2" } },
    { params: { regionPg: "eg-2" } },
    { params: { regionPg: "eh-2" } },
    { params: { regionPg: "er-2" } },
    { params: { regionPg: "es-2" } },
    { params: { regionPg: "et-2" } },
    { params: { regionPg: "fi-2" } },
    { params: { regionPg: "fj-2" } },
    { params: { regionPg: "fk-2" } },
    { params: { regionPg: "fm-2" } },
    { params: { regionPg: "fo-2" } },
    { params: { regionPg: "fr-2" } },
    { params: { regionPg: "ga-2" } },
    { params: { regionPg: "gb-2" } },
    { params: { regionPg: "gd-2" } },
    { params: { regionPg: "ge-2" } },
    { params: { regionPg: "gf-2" } },
    { params: { regionPg: "gg-2" } },
    { params: { regionPg: "gh-2" } },
    { params: { regionPg: "gi-2" } },
    { params: { regionPg: "gl-2" } },
    { params: { regionPg: "gm-2" } },
    { params: { regionPg: "gn-2" } },
    { params: { regionPg: "gp-2" } },
    { params: { regionPg: "gq-2" } },
    { params: { regionPg: "gr-2" } },
    { params: { regionPg: "gs-2" } },
    { params: { regionPg: "gt-2" } },
    { params: { regionPg: "gu-2" } },
    { params: { regionPg: "gw-2" } },
    { params: { regionPg: "gy-2" } },
    { params: { regionPg: "hk-2" } },
    { params: { regionPg: "hm-2" } },
    { params: { regionPg: "hn-2" } },
    { params: { regionPg: "hr-2" } },
    { params: { regionPg: "ht-2" } },
    { params: { regionPg: "hu-2" } },
    { params: { regionPg: "id-2" } },
    { params: { regionPg: "ie-2" } },
    { params: { regionPg: "il-2" } },
    { params: { regionPg: "im-2" } },
    { params: { regionPg: "in-2" } },
    { params: { regionPg: "io-2" } },
    { params: { regionPg: "iq-2" } },
    { params: { regionPg: "ir-2" } },
    { params: { regionPg: "is-2" } },
    { params: { regionPg: "it-2" } },
    { params: { regionPg: "je-2" } },
    { params: { regionPg: "jm-2" } },
    { params: { regionPg: "jo-2" } },
    { params: { regionPg: "jp-2" } },
    { params: { regionPg: "ke-2" } },
    { params: { regionPg: "kg-2" } },
    { params: { regionPg: "kh-2" } },
    { params: { regionPg: "ki-2" } },
    { params: { regionPg: "km-2" } },
    { params: { regionPg: "kn-2" } },
    { params: { regionPg: "kp-2" } },
    { params: { regionPg: "kr-2" } },
    { params: { regionPg: "kw-2" } },
    { params: { regionPg: "ky-2" } },
    { params: { regionPg: "kz-2" } },
    { params: { regionPg: "la-2" } },
    { params: { regionPg: "lb-2" } },
    { params: { regionPg: "lc-2" } },
    { params: { regionPg: "li-2" } },
    { params: { regionPg: "lk-2" } },
    { params: { regionPg: "lr-2" } },
    { params: { regionPg: "ls-2" } },
    { params: { regionPg: "lt-2" } },
    { params: { regionPg: "lu-2" } },
    { params: { regionPg: "lv-2" } },
    { params: { regionPg: "ly-2" } },
    { params: { regionPg: "ma-2" } },
    { params: { regionPg: "mc-2" } },
    { params: { regionPg: "md-2" } },
    { params: { regionPg: "me-2" } },
    { params: { regionPg: "mf-2" } },
    { params: { regionPg: "mg-2" } },
    { params: { regionPg: "mh-2" } },
    { params: { regionPg: "mk-2" } },
    { params: { regionPg: "ml-2" } },
    { params: { regionPg: "mm-2" } },
    { params: { regionPg: "mn-2" } },
    { params: { regionPg: "mo-2" } },
    { params: { regionPg: "mp-2" } },
    { params: { regionPg: "mq-2" } },
    { params: { regionPg: "mr-2" } },
    { params: { regionPg: "ms-2" } },
    { params: { regionPg: "mt-2" } },
    { params: { regionPg: "mu-2" } },
    { params: { regionPg: "mv-2" } },
    { params: { regionPg: "mw-2" } },
    { params: { regionPg: "mx-2" } },
    { params: { regionPg: "my-2" } },
    { params: { regionPg: "mz-2" } },
    { params: { regionPg: "na-2" } },
    { params: { regionPg: "nc-2" } },
    { params: { regionPg: "ne-2" } },
    { params: { regionPg: "nf-2" } },
    { params: { regionPg: "ng-2" } },
    { params: { regionPg: "ni-2" } },
    { params: { regionPg: "nl-2" } },
    { params: { regionPg: "no-2" } },
    { params: { regionPg: "np-2" } },
    { params: { regionPg: "nr-2" } },
    { params: { regionPg: "nu-2" } },
    { params: { regionPg: "nz-2" } },
    { params: { regionPg: "om-2" } },
    { params: { regionPg: "pa-2" } },
    { params: { regionPg: "pe-2" } },
    { params: { regionPg: "pf-2" } },
    { params: { regionPg: "pg-2" } },
    { params: { regionPg: "ph-2" } },
    { params: { regionPg: "pk-2" } },
    { params: { regionPg: "pl-2" } },
    { params: { regionPg: "pm-2" } },
    { params: { regionPg: "pn-2" } },
    { params: { regionPg: "pr-2" } },
    { params: { regionPg: "ps-2" } },
    { params: { regionPg: "pt-2" } },
    { params: { regionPg: "pw-2" } },
    { params: { regionPg: "py-2" } },
    { params: { regionPg: "qa-2" } },
    { params: { regionPg: "re-2" } },
    { params: { regionPg: "ro-2" } },
    { params: { regionPg: "rs-2" } },
    { params: { regionPg: "ru-2" } },
    { params: { regionPg: "rw-2" } },
    { params: { regionPg: "sa-2" } },
    { params: { regionPg: "sb-2" } },
    { params: { regionPg: "sc-2" } },
    { params: { regionPg: "sd-2" } },
    { params: { regionPg: "se-2" } },
    { params: { regionPg: "sg-2" } },
    { params: { regionPg: "sh-2" } },
    { params: { regionPg: "si-2" } },
    { params: { regionPg: "sj-2" } },
    { params: { regionPg: "sk-2" } },
    { params: { regionPg: "sl-2" } },
    { params: { regionPg: "sm-2" } },
    { params: { regionPg: "sn-2" } },
    { params: { regionPg: "so-2" } },
    { params: { regionPg: "sr-2" } },
    { params: { regionPg: "ss-2" } },
    { params: { regionPg: "st-2" } },
    { params: { regionPg: "sv-2" } },
    { params: { regionPg: "sx-2" } },
    { params: { regionPg: "sy-2" } },
    { params: { regionPg: "sz-2" } },
    { params: { regionPg: "tc-2" } },
    { params: { regionPg: "td-2" } },
    { params: { regionPg: "tf-2" } },
    { params: { regionPg: "tg-2" } },
    { params: { regionPg: "th-2" } },
    { params: { regionPg: "tj-2" } },
    { params: { regionPg: "tk-2" } },
    { params: { regionPg: "tl-2" } },
    { params: { regionPg: "tm-2" } },
    { params: { regionPg: "tn-2" } },
    { params: { regionPg: "to-2" } },
    { params: { regionPg: "tr-2" } },
    { params: { regionPg: "tt-2" } },
    { params: { regionPg: "tv-2" } },
    { params: { regionPg: "tw-2" } },
    { params: { regionPg: "tz-2" } },
    { params: { regionPg: "ua-2" } },
    { params: { regionPg: "ug-2" } },
    { params: { regionPg: "um-2" } },
    { params: { regionPg: "us-2" } },
    { params: { regionPg: "uy-2" } },
    { params: { regionPg: "uz-2" } },
    { params: { regionPg: "va-2" } },
    { params: { regionPg: "vc-2" } },
    { params: { regionPg: "ve-2" } },
    { params: { regionPg: "vg-2" } },
    { params: { regionPg: "vi-2" } },
    { params: { regionPg: "vn-2" } },
    { params: { regionPg: "vu-2" } },
    { params: { regionPg: "wf-2" } },
    { params: { regionPg: "ws-2" } },
    { params: { regionPg: "xk-2" } },
    { params: { regionPg: "ye-2" } },
    { params: { regionPg: "yt-2" } },
    { params: { regionPg: "za-2" } },
    { params: { regionPg: "zm-2" } },
    { params: { regionPg: "zw-2" } },
    { params: { regionPg: "ad-3" } },
    { params: { regionPg: "ae-3" } },
    { params: { regionPg: "af-3" } },
    { params: { regionPg: "ag-3" } },
    { params: { regionPg: "ai-3" } },
    { params: { regionPg: "al-3" } },
    { params: { regionPg: "am-3" } },
    { params: { regionPg: "ao-3" } },
    { params: { regionPg: "aq-3" } },
    { params: { regionPg: "ar-3" } },
    { params: { regionPg: "as-3" } },
    { params: { regionPg: "at-3" } },
    { params: { regionPg: "au-3" } },
    { params: { regionPg: "aw-3" } },
    { params: { regionPg: "ax-3" } },
    { params: { regionPg: "az-3" } },
    { params: { regionPg: "ba-3" } },
    { params: { regionPg: "bb-3" } },
    { params: { regionPg: "bd-3" } },
    { params: { regionPg: "be-3" } },
    { params: { regionPg: "bf-3" } },
    { params: { regionPg: "bg-3" } },
    { params: { regionPg: "bh-3" } },
    { params: { regionPg: "bi-3" } },
    { params: { regionPg: "bj-3" } },
    { params: { regionPg: "bl-3" } },
    { params: { regionPg: "bm-3" } },
    { params: { regionPg: "bn-3" } },
    { params: { regionPg: "bo-3" } },
    { params: { regionPg: "bq-3" } },
    { params: { regionPg: "br-3" } },
    { params: { regionPg: "bs-3" } },
    { params: { regionPg: "bt-3" } },
    { params: { regionPg: "bv-3" } },
    { params: { regionPg: "bw-3" } },
    { params: { regionPg: "by-3" } },
    { params: { regionPg: "bz-3" } },
    { params: { regionPg: "ca-3" } },
    { params: { regionPg: "cc-3" } },
    { params: { regionPg: "cd-3" } },
    { params: { regionPg: "cf-3" } },
    { params: { regionPg: "cg-3" } },
    { params: { regionPg: "ch-3" } },
    { params: { regionPg: "ci-3" } },
    { params: { regionPg: "ck-3" } },
    { params: { regionPg: "cl-3" } },
    { params: { regionPg: "cm-3" } },
    { params: { regionPg: "cn-3" } },
    { params: { regionPg: "co-3" } },
    { params: { regionPg: "cr-3" } },
    { params: { regionPg: "cu-3" } },
    { params: { regionPg: "cv-3" } },
    { params: { regionPg: "cw-3" } },
    { params: { regionPg: "cx-3" } },
    { params: { regionPg: "cy-3" } },
    { params: { regionPg: "cz-3" } },
    { params: { regionPg: "de-3" } },
    { params: { regionPg: "dj-3" } },
    { params: { regionPg: "dk-3" } },
    { params: { regionPg: "dm-3" } },
    { params: { regionPg: "do-3" } },
    { params: { regionPg: "dz-3" } },
    { params: { regionPg: "ec-3" } },
    { params: { regionPg: "ee-3" } },
    { params: { regionPg: "eg-3" } },
    { params: { regionPg: "eh-3" } },
    { params: { regionPg: "er-3" } },
    { params: { regionPg: "es-3" } },
    { params: { regionPg: "et-3" } },
    { params: { regionPg: "fi-3" } },
    { params: { regionPg: "fj-3" } },
    { params: { regionPg: "fk-3" } },
    { params: { regionPg: "fm-3" } },
    { params: { regionPg: "fo-3" } },
    { params: { regionPg: "fr-3" } },
    { params: { regionPg: "ga-3" } },
    { params: { regionPg: "gb-3" } },
    { params: { regionPg: "gd-3" } },
    { params: { regionPg: "ge-3" } },
    { params: { regionPg: "gf-3" } },
    { params: { regionPg: "gg-3" } },
    { params: { regionPg: "gh-3" } },
    { params: { regionPg: "gi-3" } },
    { params: { regionPg: "gl-3" } },
    { params: { regionPg: "gm-3" } },
    { params: { regionPg: "gn-3" } },
    { params: { regionPg: "gp-3" } },
    { params: { regionPg: "gq-3" } },
    { params: { regionPg: "gr-3" } },
    { params: { regionPg: "gs-3" } },
    { params: { regionPg: "gt-3" } },
    { params: { regionPg: "gu-3" } },
    { params: { regionPg: "gw-3" } },
    { params: { regionPg: "gy-3" } },
    { params: { regionPg: "hk-3" } },
    { params: { regionPg: "hm-3" } },
    { params: { regionPg: "hn-3" } },
    { params: { regionPg: "hr-3" } },
    { params: { regionPg: "ht-3" } },
    { params: { regionPg: "hu-3" } },
    { params: { regionPg: "id-3" } },
    { params: { regionPg: "ie-3" } },
    { params: { regionPg: "il-3" } },
    { params: { regionPg: "im-3" } },
    { params: { regionPg: "in-3" } },
    { params: { regionPg: "io-3" } },
    { params: { regionPg: "iq-3" } },
    { params: { regionPg: "ir-3" } },
    { params: { regionPg: "is-3" } },
    { params: { regionPg: "it-3" } },
    { params: { regionPg: "je-3" } },
    { params: { regionPg: "jm-3" } },
    { params: { regionPg: "jo-3" } },
    { params: { regionPg: "jp-3" } },
    { params: { regionPg: "ke-3" } },
    { params: { regionPg: "kg-3" } },
    { params: { regionPg: "kh-3" } },
    { params: { regionPg: "ki-3" } },
    { params: { regionPg: "km-3" } },
    { params: { regionPg: "kn-3" } },
    { params: { regionPg: "kp-3" } },
    { params: { regionPg: "kr-3" } },
    { params: { regionPg: "kw-3" } },
    { params: { regionPg: "ky-3" } },
    { params: { regionPg: "kz-3" } },
    { params: { regionPg: "la-3" } },
    { params: { regionPg: "lb-3" } },
    { params: { regionPg: "lc-3" } },
    { params: { regionPg: "li-3" } },
    { params: { regionPg: "lk-3" } },
    { params: { regionPg: "lr-3" } },
    { params: { regionPg: "ls-3" } },
    { params: { regionPg: "lt-3" } },
    { params: { regionPg: "lu-3" } },
    { params: { regionPg: "lv-3" } },
    { params: { regionPg: "ly-3" } },
    { params: { regionPg: "ma-3" } },
    { params: { regionPg: "mc-3" } },
    { params: { regionPg: "md-3" } },
    { params: { regionPg: "me-3" } },
    { params: { regionPg: "mf-3" } },
    { params: { regionPg: "mg-3" } },
    { params: { regionPg: "mh-3" } },
    { params: { regionPg: "mk-3" } },
    { params: { regionPg: "ml-3" } },
    { params: { regionPg: "mm-3" } },
    { params: { regionPg: "mn-3" } },
    { params: { regionPg: "mo-3" } },
    { params: { regionPg: "mp-3" } },
    { params: { regionPg: "mq-3" } },
    { params: { regionPg: "mr-3" } },
    { params: { regionPg: "ms-3" } },
    { params: { regionPg: "mt-3" } },
    { params: { regionPg: "mu-3" } },
    { params: { regionPg: "mv-3" } },
    { params: { regionPg: "mw-3" } },
    { params: { regionPg: "mx-3" } },
    { params: { regionPg: "my-3" } },
    { params: { regionPg: "mz-3" } },
    { params: { regionPg: "na-3" } },
    { params: { regionPg: "nc-3" } },
    { params: { regionPg: "ne-3" } },
    { params: { regionPg: "nf-3" } },
    { params: { regionPg: "ng-3" } },
    { params: { regionPg: "ni-3" } },
    { params: { regionPg: "nl-3" } },
    { params: { regionPg: "no-3" } },
    { params: { regionPg: "np-3" } },
    { params: { regionPg: "nr-3" } },
    { params: { regionPg: "nu-3" } },
    { params: { regionPg: "nz-3" } },
    { params: { regionPg: "om-3" } },
    { params: { regionPg: "pa-3" } },
    { params: { regionPg: "pe-3" } },
    { params: { regionPg: "pf-3" } },
    { params: { regionPg: "pg-3" } },
    { params: { regionPg: "ph-3" } },
    { params: { regionPg: "pk-3" } },
    { params: { regionPg: "pl-3" } },
    { params: { regionPg: "pm-3" } },
    { params: { regionPg: "pn-3" } },
    { params: { regionPg: "pr-3" } },
    { params: { regionPg: "ps-3" } },
    { params: { regionPg: "pt-3" } },
    { params: { regionPg: "pw-3" } },
    { params: { regionPg: "py-3" } },
    { params: { regionPg: "qa-3" } },
    { params: { regionPg: "re-3" } },
    { params: { regionPg: "ro-3" } },
    { params: { regionPg: "rs-3" } },
    { params: { regionPg: "ru-3" } },
    { params: { regionPg: "rw-3" } },
    { params: { regionPg: "sa-3" } },
    { params: { regionPg: "sb-3" } },
    { params: { regionPg: "sc-3" } },
    { params: { regionPg: "sd-3" } },
    { params: { regionPg: "se-3" } },
    { params: { regionPg: "sg-3" } },
    { params: { regionPg: "sh-3" } },
    { params: { regionPg: "si-3" } },
    { params: { regionPg: "sj-3" } },
    { params: { regionPg: "sk-3" } },
    { params: { regionPg: "sl-3" } },
    { params: { regionPg: "sm-3" } },
    { params: { regionPg: "sn-3" } },
    { params: { regionPg: "so-3" } },
    { params: { regionPg: "sr-3" } },
    { params: { regionPg: "ss-3" } },
    { params: { regionPg: "st-3" } },
    { params: { regionPg: "sv-3" } },
    { params: { regionPg: "sx-3" } },
    { params: { regionPg: "sy-3" } },
    { params: { regionPg: "sz-3" } },
    { params: { regionPg: "tc-3" } },
    { params: { regionPg: "td-3" } },
    { params: { regionPg: "tf-3" } },
    { params: { regionPg: "tg-3" } },
    { params: { regionPg: "th-3" } },
    { params: { regionPg: "tj-3" } },
    { params: { regionPg: "tk-3" } },
    { params: { regionPg: "tl-3" } },
    { params: { regionPg: "tm-3" } },
    { params: { regionPg: "tn-3" } },
    { params: { regionPg: "to-3" } },
    { params: { regionPg: "tr-3" } },
    { params: { regionPg: "tt-3" } },
    { params: { regionPg: "tv-3" } },
    { params: { regionPg: "tw-3" } },
    { params: { regionPg: "tz-3" } },
    { params: { regionPg: "ua-3" } },
    { params: { regionPg: "ug-3" } },
    { params: { regionPg: "um-3" } },
    { params: { regionPg: "us-3" } },
    { params: { regionPg: "uy-3" } },
    { params: { regionPg: "uz-3" } },
    { params: { regionPg: "va-3" } },
    { params: { regionPg: "vc-3" } },
    { params: { regionPg: "ve-3" } },
    { params: { regionPg: "vg-3" } },
    { params: { regionPg: "vi-3" } },
    { params: { regionPg: "vn-3" } },
    { params: { regionPg: "vu-3" } },
    { params: { regionPg: "wf-3" } },
    { params: { regionPg: "ws-3" } },
    { params: { regionPg: "xk-3" } },
    { params: { regionPg: "ye-3" } },
    { params: { regionPg: "yt-3" } },
    { params: { regionPg: "za-3" } },
    { params: { regionPg: "zm-3" } },
    { params: { regionPg: "zw-3" } },
    { params: { regionPg: "ad-4" } },
    { params: { regionPg: "ae-4" } },
    { params: { regionPg: "af-4" } },
    { params: { regionPg: "ag-4" } },
    { params: { regionPg: "ai-4" } },
    { params: { regionPg: "al-4" } },
    { params: { regionPg: "am-4" } },
    { params: { regionPg: "ao-4" } },
    { params: { regionPg: "aq-4" } },
    { params: { regionPg: "ar-4" } },
    { params: { regionPg: "as-4" } },
    { params: { regionPg: "at-4" } },
    { params: { regionPg: "au-4" } },
    { params: { regionPg: "aw-4" } },
    { params: { regionPg: "ax-4" } },
    { params: { regionPg: "az-4" } },
    { params: { regionPg: "ba-4" } },
    { params: { regionPg: "bb-4" } },
    { params: { regionPg: "bd-4" } },
    { params: { regionPg: "be-4" } },
    { params: { regionPg: "bf-4" } },
    { params: { regionPg: "bg-4" } },
    { params: { regionPg: "bh-4" } },
    { params: { regionPg: "bi-4" } },
    { params: { regionPg: "bj-4" } },
    { params: { regionPg: "bl-4" } },
    { params: { regionPg: "bm-4" } },
    { params: { regionPg: "bn-4" } },
    { params: { regionPg: "bo-4" } },
    { params: { regionPg: "bq-4" } },
    { params: { regionPg: "br-4" } },
    { params: { regionPg: "bs-4" } },
    { params: { regionPg: "bt-4" } },
    { params: { regionPg: "bv-4" } },
    { params: { regionPg: "bw-4" } },
    { params: { regionPg: "by-4" } },
    { params: { regionPg: "bz-4" } },
    { params: { regionPg: "ca-4" } },
    { params: { regionPg: "cc-4" } },
    { params: { regionPg: "cd-4" } },
    { params: { regionPg: "cf-4" } },
    { params: { regionPg: "cg-4" } },
    { params: { regionPg: "ch-4" } },
    { params: { regionPg: "ci-4" } },
    { params: { regionPg: "ck-4" } },
    { params: { regionPg: "cl-4" } },
    { params: { regionPg: "cm-4" } },
    { params: { regionPg: "cn-4" } },
    { params: { regionPg: "co-4" } },
    { params: { regionPg: "cr-4" } },
    { params: { regionPg: "cu-4" } },
    { params: { regionPg: "cv-4" } },
    { params: { regionPg: "cw-4" } },
    { params: { regionPg: "cx-4" } },
    { params: { regionPg: "cy-4" } },
    { params: { regionPg: "cz-4" } },
    { params: { regionPg: "de-4" } },
    { params: { regionPg: "dj-4" } },
    { params: { regionPg: "dk-4" } },
    { params: { regionPg: "dm-4" } },
    { params: { regionPg: "do-4" } },
    { params: { regionPg: "dz-4" } },
    { params: { regionPg: "ec-4" } },
    { params: { regionPg: "ee-4" } },
    { params: { regionPg: "eg-4" } },
    { params: { regionPg: "eh-4" } },
    { params: { regionPg: "er-4" } },
    { params: { regionPg: "es-4" } },
    { params: { regionPg: "et-4" } },
    { params: { regionPg: "fi-4" } },
    { params: { regionPg: "fj-4" } },
    { params: { regionPg: "fk-4" } },
    { params: { regionPg: "fm-4" } },
    { params: { regionPg: "fo-4" } },
    { params: { regionPg: "fr-4" } },
    { params: { regionPg: "ga-4" } },
    { params: { regionPg: "gb-4" } },
    { params: { regionPg: "gd-4" } },
    { params: { regionPg: "ge-4" } },
    { params: { regionPg: "gf-4" } },
    { params: { regionPg: "gg-4" } },
    { params: { regionPg: "gh-4" } },
    { params: { regionPg: "gi-4" } },
    { params: { regionPg: "gl-4" } },
    { params: { regionPg: "gm-4" } },
    { params: { regionPg: "gn-4" } },
    { params: { regionPg: "gp-4" } },
    { params: { regionPg: "gq-4" } },
    { params: { regionPg: "gr-4" } },
    { params: { regionPg: "gs-4" } },
    { params: { regionPg: "gt-4" } },
    { params: { regionPg: "gu-4" } },
    { params: { regionPg: "gw-4" } },
    { params: { regionPg: "gy-4" } },
    { params: { regionPg: "hk-4" } },
    { params: { regionPg: "hm-4" } },
    { params: { regionPg: "hn-4" } },
    { params: { regionPg: "hr-4" } },
    { params: { regionPg: "ht-4" } },
    { params: { regionPg: "hu-4" } },
    { params: { regionPg: "id-4" } },
    { params: { regionPg: "ie-4" } },
    { params: { regionPg: "il-4" } },
    { params: { regionPg: "im-4" } },
    { params: { regionPg: "in-4" } },
    { params: { regionPg: "io-4" } },
    { params: { regionPg: "iq-4" } },
    { params: { regionPg: "ir-4" } },
    { params: { regionPg: "is-4" } },
    { params: { regionPg: "it-4" } },
    { params: { regionPg: "je-4" } },
    { params: { regionPg: "jm-4" } },
    { params: { regionPg: "jo-4" } },
    { params: { regionPg: "jp-4" } },
    { params: { regionPg: "ke-4" } },
    { params: { regionPg: "kg-4" } },
    { params: { regionPg: "kh-4" } },
    { params: { regionPg: "ki-4" } },
    { params: { regionPg: "km-4" } },
    { params: { regionPg: "kn-4" } },
    { params: { regionPg: "kp-4" } },
    { params: { regionPg: "kr-4" } },
    { params: { regionPg: "kw-4" } },
    { params: { regionPg: "ky-4" } },
    { params: { regionPg: "kz-4" } },
    { params: { regionPg: "la-4" } },
    { params: { regionPg: "lb-4" } },
    { params: { regionPg: "lc-4" } },
    { params: { regionPg: "li-4" } },
    { params: { regionPg: "lk-4" } },
    { params: { regionPg: "lr-4" } },
    { params: { regionPg: "ls-4" } },
    { params: { regionPg: "lt-4" } },
    { params: { regionPg: "lu-4" } },
    { params: { regionPg: "lv-4" } },
    { params: { regionPg: "ly-4" } },
    { params: { regionPg: "ma-4" } },
    { params: { regionPg: "mc-4" } },
    { params: { regionPg: "md-4" } },
    { params: { regionPg: "me-4" } },
    { params: { regionPg: "mf-4" } },
    { params: { regionPg: "mg-4" } },
    { params: { regionPg: "mh-4" } },
    { params: { regionPg: "mk-4" } },
    { params: { regionPg: "ml-4" } },
    { params: { regionPg: "mm-4" } },
    { params: { regionPg: "mn-4" } },
    { params: { regionPg: "mo-4" } },
    { params: { regionPg: "mp-4" } },
    { params: { regionPg: "mq-4" } },
    { params: { regionPg: "mr-4" } },
    { params: { regionPg: "ms-4" } },
    { params: { regionPg: "mt-4" } },
    { params: { regionPg: "mu-4" } },
    { params: { regionPg: "mv-4" } },
    { params: { regionPg: "mw-4" } },
    { params: { regionPg: "mx-4" } },
    { params: { regionPg: "my-4" } },
    { params: { regionPg: "mz-4" } },
    { params: { regionPg: "na-4" } },
    { params: { regionPg: "nc-4" } },
    { params: { regionPg: "ne-4" } },
    { params: { regionPg: "nf-4" } },
    { params: { regionPg: "ng-4" } },
    { params: { regionPg: "ni-4" } },
    { params: { regionPg: "nl-4" } },
    { params: { regionPg: "no-4" } },
    { params: { regionPg: "np-4" } },
    { params: { regionPg: "nr-4" } },
    { params: { regionPg: "nu-4" } },
    { params: { regionPg: "nz-4" } },
    { params: { regionPg: "om-4" } },
    { params: { regionPg: "pa-4" } },
    { params: { regionPg: "pe-4" } },
    { params: { regionPg: "pf-4" } },
    { params: { regionPg: "pg-4" } },
    { params: { regionPg: "ph-4" } },
    { params: { regionPg: "pk-4" } },
    { params: { regionPg: "pl-4" } },
    { params: { regionPg: "pm-4" } },
    { params: { regionPg: "pn-4" } },
    { params: { regionPg: "pr-4" } },
    { params: { regionPg: "ps-4" } },
    { params: { regionPg: "pt-4" } },
    { params: { regionPg: "pw-4" } },
    { params: { regionPg: "py-4" } },
    { params: { regionPg: "qa-4" } },
    { params: { regionPg: "re-4" } },
    { params: { regionPg: "ro-4" } },
    { params: { regionPg: "rs-4" } },
    { params: { regionPg: "ru-4" } },
    { params: { regionPg: "rw-4" } },
    { params: { regionPg: "sa-4" } },
    { params: { regionPg: "sb-4" } },
    { params: { regionPg: "sc-4" } },
    { params: { regionPg: "sd-4" } },
    { params: { regionPg: "se-4" } },
    { params: { regionPg: "sg-4" } },
    { params: { regionPg: "sh-4" } },
    { params: { regionPg: "si-4" } },
    { params: { regionPg: "sj-4" } },
    { params: { regionPg: "sk-4" } },
    { params: { regionPg: "sl-4" } },
    { params: { regionPg: "sm-4" } },
    { params: { regionPg: "sn-4" } },
    { params: { regionPg: "so-4" } },
    { params: { regionPg: "sr-4" } },
    { params: { regionPg: "ss-4" } },
    { params: { regionPg: "st-4" } },
    { params: { regionPg: "sv-4" } },
    { params: { regionPg: "sx-4" } },
    { params: { regionPg: "sy-4" } },
    { params: { regionPg: "sz-4" } },
    { params: { regionPg: "tc-4" } },
    { params: { regionPg: "td-4" } },
    { params: { regionPg: "tf-4" } },
    { params: { regionPg: "tg-4" } },
    { params: { regionPg: "th-4" } },
    { params: { regionPg: "tj-4" } },
    { params: { regionPg: "tk-4" } },
    { params: { regionPg: "tl-4" } },
    { params: { regionPg: "tm-4" } },
    { params: { regionPg: "tn-4" } },
    { params: { regionPg: "to-4" } },
    { params: { regionPg: "tr-4" } },
    { params: { regionPg: "tt-4" } },
    { params: { regionPg: "tv-4" } },
    { params: { regionPg: "tw-4" } },
    { params: { regionPg: "tz-4" } },
    { params: { regionPg: "ua-4" } },
    { params: { regionPg: "ug-4" } },
    { params: { regionPg: "um-4" } },
    { params: { regionPg: "us-4" } },
    { params: { regionPg: "uy-4" } },
    { params: { regionPg: "uz-4" } },
    { params: { regionPg: "va-4" } },
    { params: { regionPg: "vc-4" } },
    { params: { regionPg: "ve-4" } },
    { params: { regionPg: "vg-4" } },
    { params: { regionPg: "vi-4" } },
    { params: { regionPg: "vn-4" } },
    { params: { regionPg: "vu-4" } },
    { params: { regionPg: "wf-4" } },
    { params: { regionPg: "ws-4" } },
    { params: { regionPg: "xk-4" } },
    { params: { regionPg: "ye-4" } },
    { params: { regionPg: "yt-4" } },
    { params: { regionPg: "za-4" } },
    { params: { regionPg: "zm-4" } },
    { params: { regionPg: "zw-4" } },
    { params: { regionPg: "ad-5" } },
    { params: { regionPg: "ae-5" } },
    { params: { regionPg: "af-5" } },
    { params: { regionPg: "ag-5" } },
    { params: { regionPg: "ai-5" } },
    { params: { regionPg: "al-5" } },
    { params: { regionPg: "am-5" } },
    { params: { regionPg: "ao-5" } },
    { params: { regionPg: "aq-5" } },
    { params: { regionPg: "ar-5" } },
    { params: { regionPg: "as-5" } },
    { params: { regionPg: "at-5" } },
    { params: { regionPg: "au-5" } },
    { params: { regionPg: "aw-5" } },
    { params: { regionPg: "ax-5" } },
    { params: { regionPg: "az-5" } },
    { params: { regionPg: "ba-5" } },
    { params: { regionPg: "bb-5" } },
    { params: { regionPg: "bd-5" } },
    { params: { regionPg: "be-5" } },
    { params: { regionPg: "bf-5" } },
    { params: { regionPg: "bg-5" } },
    { params: { regionPg: "bh-5" } },
    { params: { regionPg: "bi-5" } },
    { params: { regionPg: "bj-5" } },
    { params: { regionPg: "bl-5" } },
    { params: { regionPg: "bm-5" } },
    { params: { regionPg: "bn-5" } },
    { params: { regionPg: "bo-5" } },
    { params: { regionPg: "bq-5" } },
    { params: { regionPg: "br-5" } },
    { params: { regionPg: "bs-5" } },
    { params: { regionPg: "bt-5" } },
    { params: { regionPg: "bv-5" } },
    { params: { regionPg: "bw-5" } },
    { params: { regionPg: "by-5" } },
    { params: { regionPg: "bz-5" } },
    { params: { regionPg: "ca-5" } },
    { params: { regionPg: "cc-5" } },
    { params: { regionPg: "cd-5" } },
    { params: { regionPg: "cf-5" } },
    { params: { regionPg: "cg-5" } },
    { params: { regionPg: "ch-5" } },
    { params: { regionPg: "ci-5" } },
    { params: { regionPg: "ck-5" } },
    { params: { regionPg: "cl-5" } },
    { params: { regionPg: "cm-5" } },
    { params: { regionPg: "cn-5" } },
    { params: { regionPg: "co-5" } },
    { params: { regionPg: "cr-5" } },
    { params: { regionPg: "cu-5" } },
    { params: { regionPg: "cv-5" } },
    { params: { regionPg: "cw-5" } },
    { params: { regionPg: "cx-5" } },
    { params: { regionPg: "cy-5" } },
    { params: { regionPg: "cz-5" } },
    { params: { regionPg: "de-5" } },
    { params: { regionPg: "dj-5" } },
    { params: { regionPg: "dk-5" } },
    { params: { regionPg: "dm-5" } },
    { params: { regionPg: "do-5" } },
    { params: { regionPg: "dz-5" } },
    { params: { regionPg: "ec-5" } },
    { params: { regionPg: "ee-5" } },
    { params: { regionPg: "eg-5" } },
    { params: { regionPg: "eh-5" } },
    { params: { regionPg: "er-5" } },
    { params: { regionPg: "es-5" } },
    { params: { regionPg: "et-5" } },
    { params: { regionPg: "fi-5" } },
    { params: { regionPg: "fj-5" } },
    { params: { regionPg: "fk-5" } },
    { params: { regionPg: "fm-5" } },
    { params: { regionPg: "fo-5" } },
    { params: { regionPg: "fr-5" } },
    { params: { regionPg: "ga-5" } },
    { params: { regionPg: "gb-5" } },
    { params: { regionPg: "gd-5" } },
    { params: { regionPg: "ge-5" } },
    { params: { regionPg: "gf-5" } },
    { params: { regionPg: "gg-5" } },
    { params: { regionPg: "gh-5" } },
    { params: { regionPg: "gi-5" } },
    { params: { regionPg: "gl-5" } },
    { params: { regionPg: "gm-5" } },
    { params: { regionPg: "gn-5" } },
    { params: { regionPg: "gp-5" } },
    { params: { regionPg: "gq-5" } },
    { params: { regionPg: "gr-5" } },
    { params: { regionPg: "gs-5" } },
    { params: { regionPg: "gt-5" } },
    { params: { regionPg: "gu-5" } },
    { params: { regionPg: "gw-5" } },
    { params: { regionPg: "gy-5" } },
    { params: { regionPg: "hk-5" } },
    { params: { regionPg: "hm-5" } },
    { params: { regionPg: "hn-5" } },
    { params: { regionPg: "hr-5" } },
    { params: { regionPg: "ht-5" } },
    { params: { regionPg: "hu-5" } },
    { params: { regionPg: "id-5" } },
    { params: { regionPg: "ie-5" } },
    { params: { regionPg: "il-5" } },
    { params: { regionPg: "im-5" } },
    { params: { regionPg: "in-5" } },
    { params: { regionPg: "io-5" } },
    { params: { regionPg: "iq-5" } },
    { params: { regionPg: "ir-5" } },
    { params: { regionPg: "is-5" } },
    { params: { regionPg: "it-5" } },
    { params: { regionPg: "je-5" } },
    { params: { regionPg: "jm-5" } },
    { params: { regionPg: "jo-5" } },
    { params: { regionPg: "jp-5" } },
    { params: { regionPg: "ke-5" } },
    { params: { regionPg: "kg-5" } },
    { params: { regionPg: "kh-5" } },
    { params: { regionPg: "ki-5" } },
    { params: { regionPg: "km-5" } },
    { params: { regionPg: "kn-5" } },
    { params: { regionPg: "kp-5" } },
    { params: { regionPg: "kr-5" } },
    { params: { regionPg: "kw-5" } },
    { params: { regionPg: "ky-5" } },
    { params: { regionPg: "kz-5" } },
    { params: { regionPg: "la-5" } },
    { params: { regionPg: "lb-5" } },
    { params: { regionPg: "lc-5" } },
    { params: { regionPg: "li-5" } },
    { params: { regionPg: "lk-5" } },
    { params: { regionPg: "lr-5" } },
    { params: { regionPg: "ls-5" } },
    { params: { regionPg: "lt-5" } },
    { params: { regionPg: "lu-5" } },
    { params: { regionPg: "lv-5" } },
    { params: { regionPg: "ly-5" } },
    { params: { regionPg: "ma-5" } },
    { params: { regionPg: "mc-5" } },
    { params: { regionPg: "md-5" } },
    { params: { regionPg: "me-5" } },
    { params: { regionPg: "mf-5" } },
    { params: { regionPg: "mg-5" } },
    { params: { regionPg: "mh-5" } },
    { params: { regionPg: "mk-5" } },
    { params: { regionPg: "ml-5" } },
    { params: { regionPg: "mm-5" } },
    { params: { regionPg: "mn-5" } },
    { params: { regionPg: "mo-5" } },
    { params: { regionPg: "mp-5" } },
    { params: { regionPg: "mq-5" } },
    { params: { regionPg: "mr-5" } },
    { params: { regionPg: "ms-5" } },
    { params: { regionPg: "mt-5" } },
    { params: { regionPg: "mu-5" } },
    { params: { regionPg: "mv-5" } },
    { params: { regionPg: "mw-5" } },
    { params: { regionPg: "mx-5" } },
    { params: { regionPg: "my-5" } },
    { params: { regionPg: "mz-5" } },
    { params: { regionPg: "na-5" } },
    { params: { regionPg: "nc-5" } },
    { params: { regionPg: "ne-5" } },
    { params: { regionPg: "nf-5" } },
    { params: { regionPg: "ng-5" } },
    { params: { regionPg: "ni-5" } },
    { params: { regionPg: "nl-5" } },
    { params: { regionPg: "no-5" } },
    { params: { regionPg: "np-5" } },
    { params: { regionPg: "nr-5" } },
    { params: { regionPg: "nu-5" } },
    { params: { regionPg: "nz-5" } },
    { params: { regionPg: "om-5" } },
    { params: { regionPg: "pa-5" } },
    { params: { regionPg: "pe-5" } },
    { params: { regionPg: "pf-5" } },
    { params: { regionPg: "pg-5" } },
    { params: { regionPg: "ph-5" } },
    { params: { regionPg: "pk-5" } },
    { params: { regionPg: "pl-5" } },
    { params: { regionPg: "pm-5" } },
    { params: { regionPg: "pn-5" } },
    { params: { regionPg: "pr-5" } },
    { params: { regionPg: "ps-5" } },
    { params: { regionPg: "pt-5" } },
    { params: { regionPg: "pw-5" } },
    { params: { regionPg: "py-5" } },
    { params: { regionPg: "qa-5" } },
    { params: { regionPg: "re-5" } },
    { params: { regionPg: "ro-5" } },
    { params: { regionPg: "rs-5" } },
    { params: { regionPg: "ru-5" } },
    { params: { regionPg: "rw-5" } },
    { params: { regionPg: "sa-5" } },
    { params: { regionPg: "sb-5" } },
    { params: { regionPg: "sc-5" } },
    { params: { regionPg: "sd-5" } },
    { params: { regionPg: "se-5" } },
    { params: { regionPg: "sg-5" } },
    { params: { regionPg: "sh-5" } },
    { params: { regionPg: "si-5" } },
    { params: { regionPg: "sj-5" } },
    { params: { regionPg: "sk-5" } },
    { params: { regionPg: "sl-5" } },
    { params: { regionPg: "sm-5" } },
    { params: { regionPg: "sn-5" } },
    { params: { regionPg: "so-5" } },
    { params: { regionPg: "sr-5" } },
    { params: { regionPg: "ss-5" } },
    { params: { regionPg: "st-5" } },
    { params: { regionPg: "sv-5" } },
    { params: { regionPg: "sx-5" } },
    { params: { regionPg: "sy-5" } },
    { params: { regionPg: "sz-5" } },
    { params: { regionPg: "tc-5" } },
    { params: { regionPg: "td-5" } },
    { params: { regionPg: "tf-5" } },
    { params: { regionPg: "tg-5" } },
    { params: { regionPg: "th-5" } },
    { params: { regionPg: "tj-5" } },
    { params: { regionPg: "tk-5" } },
    { params: { regionPg: "tl-5" } },
    { params: { regionPg: "tm-5" } },
    { params: { regionPg: "tn-5" } },
    { params: { regionPg: "to-5" } },
    { params: { regionPg: "tr-5" } },
    { params: { regionPg: "tt-5" } },
    { params: { regionPg: "tv-5" } },
    { params: { regionPg: "tw-5" } },
    { params: { regionPg: "tz-5" } },
    { params: { regionPg: "ua-5" } },
    { params: { regionPg: "ug-5" } },
    { params: { regionPg: "um-5" } },
    { params: { regionPg: "us-5" } },
    { params: { regionPg: "uy-5" } },
    { params: { regionPg: "uz-5" } },
    { params: { regionPg: "va-5" } },
    { params: { regionPg: "vc-5" } },
    { params: { regionPg: "ve-5" } },
    { params: { regionPg: "vg-5" } },
    { params: { regionPg: "vi-5" } },
    { params: { regionPg: "vn-5" } },
    { params: { regionPg: "vu-5" } },
    { params: { regionPg: "wf-5" } },
    { params: { regionPg: "ws-5" } },
    { params: { regionPg: "xk-5" } },
    { params: { regionPg: "ye-5" } },
    { params: { regionPg: "yt-5" } },
    { params: { regionPg: "za-5" } },
    { params: { regionPg: "zm-5" } },
    { params: { regionPg: "zw-5" } },
    { params: { regionPg: "ad-6" } },
    { params: { regionPg: "ae-6" } },
    { params: { regionPg: "af-6" } },
    { params: { regionPg: "ag-6" } },
    { params: { regionPg: "ai-6" } },
    { params: { regionPg: "al-6" } },
    { params: { regionPg: "am-6" } },
    { params: { regionPg: "ao-6" } },
    { params: { regionPg: "aq-6" } },
    { params: { regionPg: "ar-6" } },
    { params: { regionPg: "as-6" } },
    { params: { regionPg: "at-6" } },
    { params: { regionPg: "au-6" } },
    { params: { regionPg: "aw-6" } },
    { params: { regionPg: "ax-6" } },
    { params: { regionPg: "az-6" } },
    { params: { regionPg: "ba-6" } },
    { params: { regionPg: "bb-6" } },
    { params: { regionPg: "bd-6" } },
    { params: { regionPg: "be-6" } },
    { params: { regionPg: "bf-6" } },
    { params: { regionPg: "bg-6" } },
    { params: { regionPg: "bh-6" } },
    { params: { regionPg: "bi-6" } },
    { params: { regionPg: "bj-6" } },
    { params: { regionPg: "bl-6" } },
    { params: { regionPg: "bm-6" } },
    { params: { regionPg: "bn-6" } },
    { params: { regionPg: "bo-6" } },
    { params: { regionPg: "bq-6" } },
    { params: { regionPg: "br-6" } },
    { params: { regionPg: "bs-6" } },
    { params: { regionPg: "bt-6" } },
    { params: { regionPg: "bv-6" } },
    { params: { regionPg: "bw-6" } },
    { params: { regionPg: "by-6" } },
    { params: { regionPg: "bz-6" } },
    { params: { regionPg: "ca-6" } },
    { params: { regionPg: "cc-6" } },
    { params: { regionPg: "cd-6" } },
    { params: { regionPg: "cf-6" } },
    { params: { regionPg: "cg-6" } },
    { params: { regionPg: "ch-6" } },
    { params: { regionPg: "ci-6" } },
    { params: { regionPg: "ck-6" } },
    { params: { regionPg: "cl-6" } },
    { params: { regionPg: "cm-6" } },
    { params: { regionPg: "cn-6" } },
    { params: { regionPg: "co-6" } },
    { params: { regionPg: "cr-6" } },
    { params: { regionPg: "cu-6" } },
    { params: { regionPg: "cv-6" } },
    { params: { regionPg: "cw-6" } },
    { params: { regionPg: "cx-6" } },
    { params: { regionPg: "cy-6" } },
    { params: { regionPg: "cz-6" } },
    { params: { regionPg: "de-6" } },
    { params: { regionPg: "dj-6" } },
    { params: { regionPg: "dk-6" } },
    { params: { regionPg: "dm-6" } },
    { params: { regionPg: "do-6" } },
    { params: { regionPg: "dz-6" } },
    { params: { regionPg: "ec-6" } },
    { params: { regionPg: "ee-6" } },
    { params: { regionPg: "eg-6" } },
    { params: { regionPg: "eh-6" } },
    { params: { regionPg: "er-6" } },
    { params: { regionPg: "es-6" } },
    { params: { regionPg: "et-6" } },
    { params: { regionPg: "fi-6" } },
    { params: { regionPg: "fj-6" } },
    { params: { regionPg: "fk-6" } },
    { params: { regionPg: "fm-6" } },
    { params: { regionPg: "fo-6" } },
    { params: { regionPg: "fr-6" } },
    { params: { regionPg: "ga-6" } },
    { params: { regionPg: "gb-6" } },
    { params: { regionPg: "gd-6" } },
    { params: { regionPg: "ge-6" } },
    { params: { regionPg: "gf-6" } },
    { params: { regionPg: "gg-6" } },
    { params: { regionPg: "gh-6" } },
    { params: { regionPg: "gi-6" } },
    { params: { regionPg: "gl-6" } },
    { params: { regionPg: "gm-6" } },
    { params: { regionPg: "gn-6" } },
    { params: { regionPg: "gp-6" } },
    { params: { regionPg: "gq-6" } },
    { params: { regionPg: "gr-6" } },
    { params: { regionPg: "gs-6" } },
    { params: { regionPg: "gt-6" } },
    { params: { regionPg: "gu-6" } },
    { params: { regionPg: "gw-6" } },
    { params: { regionPg: "gy-6" } },
    { params: { regionPg: "hk-6" } },
    { params: { regionPg: "hm-6" } },
    { params: { regionPg: "hn-6" } },
    { params: { regionPg: "hr-6" } },
    { params: { regionPg: "ht-6" } },
    { params: { regionPg: "hu-6" } },
    { params: { regionPg: "id-6" } },
    { params: { regionPg: "ie-6" } },
    { params: { regionPg: "il-6" } },
    { params: { regionPg: "im-6" } },
    { params: { regionPg: "in-6" } },
    { params: { regionPg: "io-6" } },
    { params: { regionPg: "iq-6" } },
    { params: { regionPg: "ir-6" } },
    { params: { regionPg: "is-6" } },
    { params: { regionPg: "it-6" } },
    { params: { regionPg: "je-6" } },
    { params: { regionPg: "jm-6" } },
    { params: { regionPg: "jo-6" } },
    { params: { regionPg: "jp-6" } },
    { params: { regionPg: "ke-6" } },
    { params: { regionPg: "kg-6" } },
    { params: { regionPg: "kh-6" } },
    { params: { regionPg: "ki-6" } },
    { params: { regionPg: "km-6" } },
    { params: { regionPg: "kn-6" } },
    { params: { regionPg: "kp-6" } },
    { params: { regionPg: "kr-6" } },
    { params: { regionPg: "kw-6" } },
    { params: { regionPg: "ky-6" } },
    { params: { regionPg: "kz-6" } },
    { params: { regionPg: "la-6" } },
    { params: { regionPg: "lb-6" } },
    { params: { regionPg: "lc-6" } },
    { params: { regionPg: "li-6" } },
    { params: { regionPg: "lk-6" } },
    { params: { regionPg: "lr-6" } },
    { params: { regionPg: "ls-6" } },
    { params: { regionPg: "lt-6" } },
    { params: { regionPg: "lu-6" } },
    { params: { regionPg: "lv-6" } },
    { params: { regionPg: "ly-6" } },
    { params: { regionPg: "ma-6" } },
    { params: { regionPg: "mc-6" } },
    { params: { regionPg: "md-6" } },
    { params: { regionPg: "me-6" } },
    { params: { regionPg: "mf-6" } },
    { params: { regionPg: "mg-6" } },
    { params: { regionPg: "mh-6" } },
    { params: { regionPg: "mk-6" } },
    { params: { regionPg: "ml-6" } },
    { params: { regionPg: "mm-6" } },
    { params: { regionPg: "mn-6" } },
    { params: { regionPg: "mo-6" } },
    { params: { regionPg: "mp-6" } },
    { params: { regionPg: "mq-6" } },
    { params: { regionPg: "mr-6" } },
    { params: { regionPg: "ms-6" } },
    { params: { regionPg: "mt-6" } },
    { params: { regionPg: "mu-6" } },
    { params: { regionPg: "mv-6" } },
    { params: { regionPg: "mw-6" } },
    { params: { regionPg: "mx-6" } },
    { params: { regionPg: "my-6" } },
    { params: { regionPg: "mz-6" } },
    { params: { regionPg: "na-6" } },
    { params: { regionPg: "nc-6" } },
    { params: { regionPg: "ne-6" } },
    { params: { regionPg: "nf-6" } },
    { params: { regionPg: "ng-6" } },
    { params: { regionPg: "ni-6" } },
    { params: { regionPg: "nl-6" } },
    { params: { regionPg: "no-6" } },
    { params: { regionPg: "np-6" } },
    { params: { regionPg: "nr-6" } },
    { params: { regionPg: "nu-6" } },
    { params: { regionPg: "nz-6" } },
    { params: { regionPg: "om-6" } },
    { params: { regionPg: "pa-6" } },
    { params: { regionPg: "pe-6" } },
    { params: { regionPg: "pf-6" } },
    { params: { regionPg: "pg-6" } },
    { params: { regionPg: "ph-6" } },
    { params: { regionPg: "pk-6" } },
    { params: { regionPg: "pl-6" } },
    { params: { regionPg: "pm-6" } },
    { params: { regionPg: "pn-6" } },
    { params: { regionPg: "pr-6" } },
    { params: { regionPg: "ps-6" } },
    { params: { regionPg: "pt-6" } },
    { params: { regionPg: "pw-6" } },
    { params: { regionPg: "py-6" } },
    { params: { regionPg: "qa-6" } },
    { params: { regionPg: "re-6" } },
    { params: { regionPg: "ro-6" } },
    { params: { regionPg: "rs-6" } },
    { params: { regionPg: "ru-6" } },
    { params: { regionPg: "rw-6" } },
    { params: { regionPg: "sa-6" } },
    { params: { regionPg: "sb-6" } },
    { params: { regionPg: "sc-6" } },
    { params: { regionPg: "sd-6" } },
    { params: { regionPg: "se-6" } },
    { params: { regionPg: "sg-6" } },
    { params: { regionPg: "sh-6" } },
    { params: { regionPg: "si-6" } },
    { params: { regionPg: "sj-6" } },
    { params: { regionPg: "sk-6" } },
    { params: { regionPg: "sl-6" } },
    { params: { regionPg: "sm-6" } },
    { params: { regionPg: "sn-6" } },
    { params: { regionPg: "so-6" } },
    { params: { regionPg: "sr-6" } },
    { params: { regionPg: "ss-6" } },
    { params: { regionPg: "st-6" } },
    { params: { regionPg: "sv-6" } },
    { params: { regionPg: "sx-6" } },
    { params: { regionPg: "sy-6" } },
    { params: { regionPg: "sz-6" } },
    { params: { regionPg: "tc-6" } },
    { params: { regionPg: "td-6" } },
    { params: { regionPg: "tf-6" } },
    { params: { regionPg: "tg-6" } },
    { params: { regionPg: "th-6" } },
    { params: { regionPg: "tj-6" } },
    { params: { regionPg: "tk-6" } },
    { params: { regionPg: "tl-6" } },
    { params: { regionPg: "tm-6" } },
    { params: { regionPg: "tn-6" } },
    { params: { regionPg: "to-6" } },
    { params: { regionPg: "tr-6" } },
    { params: { regionPg: "tt-6" } },
    { params: { regionPg: "tv-6" } },
    { params: { regionPg: "tw-6" } },
    { params: { regionPg: "tz-6" } },
    { params: { regionPg: "ua-6" } },
    { params: { regionPg: "ug-6" } },
    { params: { regionPg: "um-6" } },
    { params: { regionPg: "us-6" } },
    { params: { regionPg: "uy-6" } },
    { params: { regionPg: "uz-6" } },
    { params: { regionPg: "va-6" } },
    { params: { regionPg: "vc-6" } },
    { params: { regionPg: "ve-6" } },
    { params: { regionPg: "vg-6" } },
    { params: { regionPg: "vi-6" } },
    { params: { regionPg: "vn-6" } },
    { params: { regionPg: "vu-6" } },
    { params: { regionPg: "wf-6" } },
    { params: { regionPg: "ws-6" } },
    { params: { regionPg: "xk-6" } },
    { params: { regionPg: "ye-6" } },
    { params: { regionPg: "yt-6" } },
    { params: { regionPg: "za-6" } },
    { params: { regionPg: "zm-6" } },
    { params: { regionPg: "zw-6" } },
    { params: { regionPg: "ad-7" } },
    { params: { regionPg: "ae-7" } },
    { params: { regionPg: "af-7" } },
    { params: { regionPg: "ag-7" } },
    { params: { regionPg: "ai-7" } },
    { params: { regionPg: "al-7" } },
    { params: { regionPg: "am-7" } },
    { params: { regionPg: "ao-7" } },
    { params: { regionPg: "aq-7" } },
    { params: { regionPg: "ar-7" } },
    { params: { regionPg: "as-7" } },
    { params: { regionPg: "at-7" } },
    { params: { regionPg: "au-7" } },
    { params: { regionPg: "aw-7" } },
    { params: { regionPg: "ax-7" } },
    { params: { regionPg: "az-7" } },
    { params: { regionPg: "ba-7" } },
    { params: { regionPg: "bb-7" } },
    { params: { regionPg: "bd-7" } },
    { params: { regionPg: "be-7" } },
    { params: { regionPg: "bf-7" } },
    { params: { regionPg: "bg-7" } },
    { params: { regionPg: "bh-7" } },
    { params: { regionPg: "bi-7" } },
    { params: { regionPg: "bj-7" } },
    { params: { regionPg: "bl-7" } },
    { params: { regionPg: "bm-7" } },
    { params: { regionPg: "bn-7" } },
    { params: { regionPg: "bo-7" } },
    { params: { regionPg: "bq-7" } },
    { params: { regionPg: "br-7" } },
    { params: { regionPg: "bs-7" } },
    { params: { regionPg: "bt-7" } },
    { params: { regionPg: "bv-7" } },
    { params: { regionPg: "bw-7" } },
    { params: { regionPg: "by-7" } },
    { params: { regionPg: "bz-7" } },
    { params: { regionPg: "ca-7" } },
    { params: { regionPg: "cc-7" } },
    { params: { regionPg: "cd-7" } },
    { params: { regionPg: "cf-7" } },
    { params: { regionPg: "cg-7" } },
    { params: { regionPg: "ch-7" } },
    { params: { regionPg: "ci-7" } },
    { params: { regionPg: "ck-7" } },
    { params: { regionPg: "cl-7" } },
    { params: { regionPg: "cm-7" } },
    { params: { regionPg: "cn-7" } },
    { params: { regionPg: "co-7" } },
    { params: { regionPg: "cr-7" } },
    { params: { regionPg: "cu-7" } },
    { params: { regionPg: "cv-7" } },
    { params: { regionPg: "cw-7" } },
    { params: { regionPg: "cx-7" } },
    { params: { regionPg: "cy-7" } },
    { params: { regionPg: "cz-7" } },
    { params: { regionPg: "de-7" } },
    { params: { regionPg: "dj-7" } },
    { params: { regionPg: "dk-7" } },
    { params: { regionPg: "dm-7" } },
    { params: { regionPg: "do-7" } },
    { params: { regionPg: "dz-7" } },
    { params: { regionPg: "ec-7" } },
    { params: { regionPg: "ee-7" } },
    { params: { regionPg: "eg-7" } },
    { params: { regionPg: "eh-7" } },
    { params: { regionPg: "er-7" } },
    { params: { regionPg: "es-7" } },
    { params: { regionPg: "et-7" } },
    { params: { regionPg: "fi-7" } },
    { params: { regionPg: "fj-7" } },
    { params: { regionPg: "fk-7" } },
    { params: { regionPg: "fm-7" } },
    { params: { regionPg: "fo-7" } },
    { params: { regionPg: "fr-7" } },
    { params: { regionPg: "ga-7" } },
    { params: { regionPg: "gb-7" } },
    { params: { regionPg: "gd-7" } },
    { params: { regionPg: "ge-7" } },
    { params: { regionPg: "gf-7" } },
    { params: { regionPg: "gg-7" } },
    { params: { regionPg: "gh-7" } },
    { params: { regionPg: "gi-7" } },
    { params: { regionPg: "gl-7" } },
    { params: { regionPg: "gm-7" } },
    { params: { regionPg: "gn-7" } },
    { params: { regionPg: "gp-7" } },
    { params: { regionPg: "gq-7" } },
    { params: { regionPg: "gr-7" } },
    { params: { regionPg: "gs-7" } },
    { params: { regionPg: "gt-7" } },
    { params: { regionPg: "gu-7" } },
    { params: { regionPg: "gw-7" } },
    { params: { regionPg: "gy-7" } },
    { params: { regionPg: "hk-7" } },
    { params: { regionPg: "hm-7" } },
    { params: { regionPg: "hn-7" } },
    { params: { regionPg: "hr-7" } },
    { params: { regionPg: "ht-7" } },
    { params: { regionPg: "hu-7" } },
    { params: { regionPg: "id-7" } },
    { params: { regionPg: "ie-7" } },
    { params: { regionPg: "il-7" } },
    { params: { regionPg: "im-7" } },
    { params: { regionPg: "in-7" } },
    { params: { regionPg: "io-7" } },
    { params: { regionPg: "iq-7" } },
    { params: { regionPg: "ir-7" } },
    { params: { regionPg: "is-7" } },
    { params: { regionPg: "it-7" } },
    { params: { regionPg: "je-7" } },
    { params: { regionPg: "jm-7" } },
    { params: { regionPg: "jo-7" } },
    { params: { regionPg: "jp-7" } },
    { params: { regionPg: "ke-7" } },
    { params: { regionPg: "kg-7" } },
    { params: { regionPg: "kh-7" } },
    { params: { regionPg: "ki-7" } },
    { params: { regionPg: "km-7" } },
    { params: { regionPg: "kn-7" } },
    { params: { regionPg: "kp-7" } },
    { params: { regionPg: "kr-7" } },
    { params: { regionPg: "kw-7" } },
    { params: { regionPg: "ky-7" } },
    { params: { regionPg: "kz-7" } },
    { params: { regionPg: "la-7" } },
    { params: { regionPg: "lb-7" } },
    { params: { regionPg: "lc-7" } },
    { params: { regionPg: "li-7" } },
    { params: { regionPg: "lk-7" } },
    { params: { regionPg: "lr-7" } },
    { params: { regionPg: "ls-7" } },
    { params: { regionPg: "lt-7" } },
    { params: { regionPg: "lu-7" } },
    { params: { regionPg: "lv-7" } },
    { params: { regionPg: "ly-7" } },
    { params: { regionPg: "ma-7" } },
    { params: { regionPg: "mc-7" } },
    { params: { regionPg: "md-7" } },
    { params: { regionPg: "me-7" } },
    { params: { regionPg: "mf-7" } },
    { params: { regionPg: "mg-7" } },
    { params: { regionPg: "mh-7" } },
    { params: { regionPg: "mk-7" } },
    { params: { regionPg: "ml-7" } },
    { params: { regionPg: "mm-7" } },
    { params: { regionPg: "mn-7" } },
    { params: { regionPg: "mo-7" } },
    { params: { regionPg: "mp-7" } },
    { params: { regionPg: "mq-7" } },
    { params: { regionPg: "mr-7" } },
    { params: { regionPg: "ms-7" } },
    { params: { regionPg: "mt-7" } },
    { params: { regionPg: "mu-7" } },
    { params: { regionPg: "mv-7" } },
    { params: { regionPg: "mw-7" } },
    { params: { regionPg: "mx-7" } },
    { params: { regionPg: "my-7" } },
    { params: { regionPg: "mz-7" } },
    { params: { regionPg: "na-7" } },
    { params: { regionPg: "nc-7" } },
    { params: { regionPg: "ne-7" } },
    { params: { regionPg: "nf-7" } },
    { params: { regionPg: "ng-7" } },
    { params: { regionPg: "ni-7" } },
    { params: { regionPg: "nl-7" } },
    { params: { regionPg: "no-7" } },
    { params: { regionPg: "np-7" } },
    { params: { regionPg: "nr-7" } },
    { params: { regionPg: "nu-7" } },
    { params: { regionPg: "nz-7" } },
    { params: { regionPg: "om-7" } },
    { params: { regionPg: "pa-7" } },
    { params: { regionPg: "pe-7" } },
    { params: { regionPg: "pf-7" } },
    { params: { regionPg: "pg-7" } },
    { params: { regionPg: "ph-7" } },
    { params: { regionPg: "pk-7" } },
    { params: { regionPg: "pl-7" } },
    { params: { regionPg: "pm-7" } },
    { params: { regionPg: "pn-7" } },
    { params: { regionPg: "pr-7" } },
    { params: { regionPg: "ps-7" } },
    { params: { regionPg: "pt-7" } },
    { params: { regionPg: "pw-7" } },
    { params: { regionPg: "py-7" } },
    { params: { regionPg: "qa-7" } },
    { params: { regionPg: "re-7" } },
    { params: { regionPg: "ro-7" } },
    { params: { regionPg: "rs-7" } },
    { params: { regionPg: "ru-7" } },
    { params: { regionPg: "rw-7" } },
    { params: { regionPg: "sa-7" } },
    { params: { regionPg: "sb-7" } },
    { params: { regionPg: "sc-7" } },
    { params: { regionPg: "sd-7" } },
    { params: { regionPg: "se-7" } },
    { params: { regionPg: "sg-7" } },
    { params: { regionPg: "sh-7" } },
    { params: { regionPg: "si-7" } },
    { params: { regionPg: "sj-7" } },
    { params: { regionPg: "sk-7" } },
    { params: { regionPg: "sl-7" } },
    { params: { regionPg: "sm-7" } },
    { params: { regionPg: "sn-7" } },
    { params: { regionPg: "so-7" } },
    { params: { regionPg: "sr-7" } },
    { params: { regionPg: "ss-7" } },
    { params: { regionPg: "st-7" } },
    { params: { regionPg: "sv-7" } },
    { params: { regionPg: "sx-7" } },
    { params: { regionPg: "sy-7" } },
    { params: { regionPg: "sz-7" } },
    { params: { regionPg: "tc-7" } },
    { params: { regionPg: "td-7" } },
    { params: { regionPg: "tf-7" } },
    { params: { regionPg: "tg-7" } },
    { params: { regionPg: "th-7" } },
    { params: { regionPg: "tj-7" } },
    { params: { regionPg: "tk-7" } },
    { params: { regionPg: "tl-7" } },
    { params: { regionPg: "tm-7" } },
    { params: { regionPg: "tn-7" } },
    { params: { regionPg: "to-7" } },
    { params: { regionPg: "tr-7" } },
    { params: { regionPg: "tt-7" } },
    { params: { regionPg: "tv-7" } },
    { params: { regionPg: "tw-7" } },
    { params: { regionPg: "tz-7" } },
    { params: { regionPg: "ua-7" } },
    { params: { regionPg: "ug-7" } },
    { params: { regionPg: "um-7" } },
    { params: { regionPg: "us-7" } },
    { params: { regionPg: "uy-7" } },
    { params: { regionPg: "uz-7" } },
    { params: { regionPg: "va-7" } },
    { params: { regionPg: "vc-7" } },
    { params: { regionPg: "ve-7" } },
    { params: { regionPg: "vg-7" } },
    { params: { regionPg: "vi-7" } },
    { params: { regionPg: "vn-7" } },
    { params: { regionPg: "vu-7" } },
    { params: { regionPg: "wf-7" } },
    { params: { regionPg: "ws-7" } },
    { params: { regionPg: "xk-7" } },
    { params: { regionPg: "ye-7" } },
    { params: { regionPg: "yt-7" } },
    { params: { regionPg: "za-7" } },
    { params: { regionPg: "zm-7" } },
    { params: { regionPg: "zw-7" } },
  ];
}

interface FavoritesPg {
  params: { favoritesPg: string };
}

export async function getFavoritesPgPaths(): Promise<FavoritesPg[]> {
  return [
    { params: { favoritesPg: "favorites-1" } },
    { params: { favoritesPg: "favorites-2" } },
    { params: { favoritesPg: "favorites-3" } },
    { params: { favoritesPg: "favorites-4" } },
    { params: { favoritesPg: "favorites-5" } },
    { params: { favoritesPg: "favorites-6" } },
    { params: { favoritesPg: "favorites-7" } },
  ];
}
